### ISSUE TITLE
2 PHP notices on latest stable release

### ISSUE THREAD

**Issue by acbramley** [davidrjonas/composer-lock-diff#24]
```
Notice: Undefined property: stdClass::$source in /data/vendor/davidrjonas/composer-lock-diff/composer-lock-diff on line 212

Notice: Trying to get property 'url' of non-object in /data/vendor/davidrjonas/composer-lock-diff/composer-lock-diff on line 212
```

I haven't dug into which packages are throwing these errors yet

**Comment by davidrjonas** [comment]
Sorry I haven’t had a chance to look at this yet. Hoping to get to it this weekend.

**Comment by davidrjonas** [comment]
It is something related to the packages you're using. Is it a public package? If so let me know, maybe there is a good way to handle it.

For now, only the compare url is at issue so skipping it if the source isn't set is not a big deal.  I made a [slight change][0] that is now in `master`. Does that fix the problem for you? If so I'll cut a release.

[0]: https://github.com/davidrjonas/composer-lock-diff/commit/76cabf422198bd62fa80f940a0f2735b3f8b7401
