### ISSUE TITLE
--from <gitref> results in lockfile not loadable

### ISSUE THREAD

**Issue by Jeroeny** [davidrjonas/composer-lock-diff#32]
Since 1.6.0 I'm experiencing the following error when trying to get the lockdiff using:

```
bin/composer-lock-diff  --md --from="refs/remotes/upstream/master:composer.lock" 
```

Results in the error:

```
Failed to find 'refs/remotes/upstream/master:composer.lock' with 'loadFile'; Candidate 'refs/remotes/upstream/master:composer.lock' does not look loadable from the fs or php stream wrappers
```

Both on windows and linux. I've also tried different refs like `HEAD:composer.lock`, `HEAD:./composer.lock` and with the `--vcs` argument. 

Or without `--from`:

```
$ ../../some/path/bin/composer-lock-diff --md
Could not find .git in current directory or parents
'svn --version' exited with non-zero code '127'
No loaders were found; perhaps your vcs cli tools are not installed, not in PATH, or otherwise unavailable
```

Even though the `.git` directory exists in the working directory. Does it matter if the composer-lock-diff binary lives in some other directory? I assume it takes the current working directory.

**Comment by davidrjonas** [comment]
I am really sorry about that. Thank you for making a report! The issues are fixed in master, as far as I can tell, and I'm making a 1.6.1 release. I need to make a better test harness!  Please reopen if you're still having trouble!
